### ISSUE TITLE
New Guild Log filters don't always update

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#102]
Sometimes when changing filters the page doesn't update and you have to refresh

**Comment by barnie995** [comment]
Reading this, it looked easier.   

For relics issue,   Un Empowerment for them has the id :  GuildLogFilter:Unknown     WHY?!!?!?!?!?

**Comment by atompkins** [comment]
I am still getting the filters not working. It usually happens the first time I look at the guild log in a session.

**Comment by atompkins** [comment]
Newly processed rows do not get row id

**Comment by barnie995** [comment]
Ive reproduced it and its really really damn weird.  Ill see if I can do it
