### ISSUE TITLE
Support Req

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#105]
00:02 31/Jul/2016
[ Report | Ignore ]		BugSlayer says: Hi there! I hope I won`t bother you byt asking this, but... I used FSH in my older laptop and it was just amazing, but since right now I`m having a few issues with it in this new computer. Some functions, like the color determining the last activity in guild member list and the quick links are not working anymore. I was wondering if you have any tips for me. P.S: In case it would matter, I`m using GoogleChrome with Tamper Monkey Installed, both up-to-date.

**Comment by LizJHankins** [comment]
I am using FF and having same problems when I go to my step daughters comp. &  use since I do not let it update works great

**Comment by atompkins** [comment]
Hunt mode was turned on
