### ISSUE TITLE
Message Preview / The message you recieved when you reply

### ISSUE THREAD

**Issue by barnie995** [fallenswordhelper/fallenswordhelper#109]
No clue what to call it, so Ill call it that.   When you hit reply, Ive noticed that sometimes it doesnt show spaces correctly or it doesnt include punctuation.

Picture should show it clearer:

![screenshot from 2016-08-18 11-56-20](https://cloud.githubusercontent.com/assets/12813908/17759579/880cd008-653b-11e6-8a09-2bd67192f039.png)

**Comment by atompkins** [comment]
Enable Chat Parsing
