### ISSUE TITLE
Inventory now miscalculates hell forge bonus

### ISSUE THREAD

**Issue by mpegdor** [fallenswordhelper/fallenswordhelper#120]
I was just comparing stats in the player inventory with actual items and noticed that the inventory was underestimating the stats for high level items. For the few I checked in detail, it appears that the inventory is applying the old (50+(5*5/50))/2 formula to fully forged 2-stat items, rather than using (10% of total item stats)/2 when this is larger.

(Rowbeth in-game)

**Comment by atompkins** [comment]
This is quite interesting. I'll have to validate, but if true, these figures come from the HCS export function so we'll need to raise a ticket.

**Comment by atompkins** [comment]
Inventory export mismatch
FS‑028178: Submitted 1 second ago

**Comment by atompkins** [comment]
which got closed today without a resolution???

**Comment by barnie995** [comment]
Could it have been closed by a helper/whatever they are called internally due to it not being a question or something that is easily solved ?

**Comment by atompkins** [comment]
One of my guildies mentioned that tickets get auto-closed after a certain periods of inactivity so I have re-opened.
