### ISSUE TITLE
Add titan info (number of kills) in world map

### ISSUE THREAD

**Issue by insaner6** [fallenswordhelper/fallenswordhelper#125]
hi there, 

when you are killing a titan, there is no way u can know what number of kills u have achived.
u have to go back to the Scout Tower, open it,  and then look for the specific titan
that u are hunting to see your progress.
During stressful hunts, that's nearly impossible..  even if u have that page on a seperate tab, it will take some valuable time.
i was wondering, if that info, can be added next to the name of the realm that i am.

depending the active titan that is in that realm, somehow to be able to copy-paste the info
from the Scout Tower.  something like the picture attached.
![gd3](https://cloud.githubusercontent.com/assets/23419225/20238637/af04644a-a8f8-11e6-9fb6-187991300022.JPG)

**Comment by atompkins** [comment]
I'm thinking we should add this to the mouse over.
Also disable combat result button and other players view button
