### ISSUE TITLE
Add Current Level to world screen

### ISSUE THREAD

**Issue by yuuzhan** [fallenswordhelper/fallenswordhelper#137]
It would be nice to put the character level on the world screen.  I keep having to mouse over to see it!

It could be added beside Min Level.

![2017-01-11_10-21-11](https://cloud.githubusercontent.com/assets/4114975/21854204/e5f08eac-d7e7-11e6-8303-23c1360b3474.png)

**Comment by atompkins** [comment]
This is what I was afraid of

![worldtitleproblem](https://cloud.githubusercontent.com/assets/6729161/25270643/402cda80-2679-11e7-9f12-6d5780741ee5.PNG)

**Comment by yuuzhan** [comment]
Can you put Min: and Lvl: on top of one another (2 rows), in a slightly smaller font?

Looks like that line has the height for it, with the bolded map name,

**Comment by atompkins** [comment]
That's a possibility. I'd be interested to know what the longest Realm name is to see how much room we may have. I've got a scraper for UFSG, just need to reproduce the font to measure the width.
I was thinking that to avoid all this I could put the FSH buttons underneath in a separate DIV. I might try that first. It would give us the whole width to play with, so I'd be able to use more descriptive labels.

But I think it looks rubbish:
![worldbuttonsnewrow](https://cloud.githubusercontent.com/assets/6729161/25304502/7b27c2a2-2760-11e7-85a2-b2eafe3f6592.PNG)
Or above
![worldbuttonsnewrowabove](https://cloud.githubusercontent.com/assets/6729161/25304518/c0d9d5ec-2760-11e7-8c0e-e011a8baae21.PNG)
Or below
![worldbuttonsnewrowbelow](https://cloud.githubusercontent.com/assets/6729161/25304541/0f85b74c-2761-11e7-82e8-5439b7f45d8c.PNG)
Underneath is less bad. I'll have a go with your idea next.

**Comment by yuuzhan** [comment]
That first one looks like a good start, but make it Left justified.

I have a UFSG Scraper too :P Really just find the longest one, and then edit any realm inline with Chrome Inspector changing the world name to be the longest name.

**Comment by atompkins** [comment]
I've stacked and shrunk it for now. It's in beta.
![worldtitlesmallfont](https://cloud.githubusercontent.com/assets/6729161/25309083/0f5d3e34-27bb-11e7-9487-c6e7d5af4e87.PNG)

**Comment by yuuzhan** [comment]
That looks much better :)

Unrelated, but if it would help prevent wrapping, would it be worth putting the icons in two rows?

**Comment by atompkins** [comment]
Good shout on the test
![worldtitlelenzwer](https://cloud.githubusercontent.com/assets/6729161/25315488/678c3dca-284d-11e7-8d7e-6a4e4d19888d.PNG)
I'll see what I can do with 2 rows. I'm sorely tempted to remove Hunt mode altogether.

**Comment by atompkins** [comment]
This is without the sound button
![worldtitlelenzwernosound](https://cloud.githubusercontent.com/assets/6729161/25315523/3120f55e-284e-11e7-87b2-ffa500198462.PNG)
Might just leave it

**Comment by yuuzhan** [comment]
looks good.

**Comment by yuuzhan** [comment]
Maybe not worth it, but you can have the user configure what buttons show up (and default some off)  Then if you get some wrapping problems, its your own fault ;)
