### ISSUE TITLE
GvG Finder

### ISSUE THREAD

**Issue by gapukas** [fallenswordhelper/fallenswordhelper#172]
Sorry, this isn't an issue but i couldnt find another way to contact. i have an idea considering guild versus guild battles - the list making usually takes hours to compose.

- Add a "Initiate conflicts" button to you're guild page that lets you start multiple conflicts(Charges for all conflicts at once upon accepting)
- At first choose you're participants in GvG's
- Then they will be matched to guilds with at least 2 attackers from your guild up to a maximum of 4 attackers and up to 20 guilds(Makes sure the guild is valid for gvg meaning there are 4 extra players besides the guild leader and the guild leader has been active within 7 days, removes players from the list who you have been in conflict with recently if the gvg cooldown applies)
- A target would not be considered if he has been unactive more than 6 days.
- Always add 1 extra participant spot (like when there are 2 attackers, max participants would be 4. on 4 it would be 5)

Thats basically it, please consider this :) its always a pain and stressing to compose the lists when you could just enter a few variables for it to be auto detected and initiated

**Comment by atompkins** [comment]
Good luck with that. Unless you want to code it yourself you'll have to talk to HCS.

**Comment by gapukas** [comment]
Thanks for the fast feedback tho, i doubt they will but i can ask them.
