### ISSUE TITLE
Hotkeys for killing champs

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#184]
20:30 26/Mar/2019  Pardoux says: Another possible implementation into the FSH ? - Hotkeys for Champions (YUIOP or GHJKL or VBNM) ?? Would that be an easy thing to do ?

**Comment by ahanden** [comment]
Thinking of implementing this using the shift-key, which will toggle between common and non-common creatures.

**Comment by ahanden** [comment]
This would override existing functionality - shift+number equips a combat set. Thoughts on replacing this?
