### ISSUE TITLE
Auction Quick Select - Rome

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#205]
[22:01] Rome: @[FFS] PointyHair Would it be very hard to add the quick select items to the create auction screen where the perfect link is, to select all of the same item for the auction?

**Comment by atompkins** [comment]
I am thinking that we can dynamically produce the quick select list instead of it being user input. There is too much room for error and you end up with a bunch of items that are not relevant.

**Comment by atompkins** [comment]
Does it need a preference?

**Comment by ahanden** [comment]
isn't this mostly taken care of by AH templates already?

**Comment by atompkins** [comment]
bit clunky and unreliable i think
