### ISSUE TITLE
Colour player names in AH/Buff Market - Thoran

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#232]
![image](https://user-images.githubusercontent.com/6729161/124625170-7c20db00-de75-11eb-9875-21b91d2ec6ae.png)

**Comment by UnoWild** [comment]
Another way of doing this could be to add a section in the menu to the left, to list links to the AH listing of all guild members, Online or Off. This way, as per above also, we can buy what we need but keep the funds (gold/FSP's) within the guild. 
This was the purpose of my suggestion today

- Thoran
