### ISSUE TITLE
Add version number to FSHelper screen so users can confirm what version they are using when submitting bug reports.

### ISSUE THREAD

**Issue by yuuzhan** [fallenswordhelper/fallenswordhelper#40]
I wrote a long title.  Would be good to create a more helpful "Send us your logs" type function that would create a text blob that they can paste here when submitting a bug report.

**Comment by atompkins** [comment]
3d683db570c77594c9cb9a97dfa4cb464a2c2b0b

**Comment by atompkins** [comment]
I've got version number in settings now, ready for next release.
What did you have in mind for the text blob?
I can tell if it's running inside TamperMonkey but not Greasemonkey or Chrome native reliably.
I can have a good guess at GreaseMonkey though using duck typing.
And probably return the userAgent??

**Comment by yuuzhan** [comment]
userAgent would be a good, I had not thought of that.

I was thinking mostly the "Save or load settings" option:

http://www.fallensword.com/index.php?cmd=notepad&blank=1&subcmd=savesettings

I would trust the user if they are using tapermonkey vs greasemonkey - just lets us load user settings into a testing environment to better notice what a user is seeing.  

Perhaps we can get native Chrome / Firefox help to give a dump of APP versions / settings.

**Comment by atompkins** [comment]
we get hardly any support requests, i'm going to close this.
