### ISSUE TITLE
Clear Storage button - (was = FS Helper settings will not save)

### ISSUE THREAD

**Issue by icd55mph** [fallenswordhelper/fallenswordhelper#58]
Version 1506. I can't get the helper settings to save. Check the boxes and hit save get the message fs helper settings saved. open preferences back up and everything is back to default.

**Comment by atompkins** [comment]
Which browser please?

**Comment by icd55mph** [comment]
Firefox 40.0.3

Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
yeah that will be why then, your storage is full.
clearing cookies is the quickest way to do it.
if you don't want to lose your settings you'll have to clear logs manually.

**Comment by icd55mph** [comment]
Thanks
Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
no problem.
Which logs do you use the most? I am deciding which one will get moved over
to the new storage system next?
I think New Guild Log is probably favourite right now.

**Comment by icd55mph** [comment]
That would work for now. I’m still clearing cookies.
Martin Hannu
icd55mph@centurylink.net

**Comment by icd55mph** [comment]
I have cleared most everything and the cash and history are at 0 bytes and I still get this (Current version: 1507) (Storage Used: 115.55% Remaining: -15.549999999999997%)
Restarted the computer also. What’s left?
Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
at the bottom of the settings page go into export or load settings
cut and paste them here.

in firefox - preferences - privacy, click on "clear your recent history",
set time range to "everything" and make sure all boxes underneath are
checked.

**Comment by icd55mph** [comment]
{"hideRecipes":false,"showWeaponTypeItems":true,"renderSelfBio":true,"playNewMessageSound":false,"listOfAllies":"","autoFillMinBidPrice":true,"footprintsColor":"silver","autoSortArenaList":false,"allyEnemyOnlineRefreshTime":300,"lastTempleCheck":0,"enableLogColoring":true,"enableAllyOnlineList":false,"showTaggingMessages":true,"keepBuffLog":false,"highlightGvGPlayersNearMyLvl":true,"showRankingMessages":true,"hideGuildInfoBuff":false,"hideNonPlayerGuildLogMessages":true,"showShieldTypeItems":true,"detailedConflictInfo":false,"showGroupCombatMessages":true,"enableActiveBountyList":false,"showExtraLinks":true,"bioEditLines":10,"quickLinks":"[]","combatEvaluatorBias":0,"showDonationMessages":true,"lastOutBoxCheck":"0","showCreatureInfo":false,"characterVirtualLevel":0,"quickSearchList":"[{\"category\":\"Plants\",\"searchname\":\"Amber\",\"nickname\":\"\"},{\"category\":\"Plants\",\"searchname\":\"Blood Bloom\",\"nickname\":\"\"},{\"category\":\"Plants\",\"searchname\":\"Jademare\",\"nickname\":\"\"},{\"category\":\"Plants\",\"searchname\":\"Dark Shade\",\"nickname\":\"\"},{\"category\":\"Plants\",\"searchname\":\"Trinettle\",\"nickname\":\"\"},{\"category\":\"Plants\",\"searchname\":\"Heffle Wart\",\"nickname\":\"\"},{\"category\":\"Potions\",\"searchname\":\"Sludge Brew\",\"nickname\":\"DC 200\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Black Death\",\"nickname\":\"DC 225\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Aid\",\"nickname\":\"Assist\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Supreme Doubling\",\"nickname\":\"DB 450\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Acceleration\",\"nickname\":\"DB 500\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Lesser Death Dealer\",\"nickname\":\"DD\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Runic Potion\",\"nickname\":\"FI 250\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of the Bookworm\",\"nickname\":\"Lib 225\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Truth\",\"nickname\":\"EW 1k\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Dull Edge\",\"nickname\":\"DE 25\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Notched Blade\",\"nickname\":\"DE 80\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Death\",\"nickname\":\"DW 125\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Decay\",\"nickname\":\"WI 150\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Fatality\",\"nickname\":\"WI 350\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Annihilation\",\"nickname\":\"DW 150\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of the Wise\",\"nickname\":\"Lib 200\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Shattering\",\"nickname\":\"SA\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Dragons Blood Potion\",\"nickname\":\"ZK 200\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Berserkers Potion\",\"nickname\":\"ZK 300\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Fury\",\"nickname\":\"ZK 350\",\"displayOnAH\":true},{\"category\":\"Potions\",\"searchname\":\"Potion of Supreme Luck\",\"nickname\":\"FI 1k\",\"displayOnAH\":true}]","showBootTypeItems":true,"quickLinksTopPx":22,"showRuneTypeItems":true,"renderOtherBios":true,"hideBuffSelected":false,"hideHelperMenu":false,"questsNotStarted":false,"huntingBuffs3":"SE hunting","newGuildLogHistoryPages":3,"quickMsg":"[\"Thank you very much ^_^\",\"Happy hunting, {playername}\"]","showNextQuestSteps":true,"showHelmetTypeItems":true,"enableMaxGroupSizeToJoin":false,"enemiestotal":0,"quickLinksLeftPx":0,"enabledHuntingMode":1,"hideArenaPrizes":"","quickKill":false,"showMercenaryMessages":true,"moveOnlineAlliesList":false,"showGloveTypeItems":true,"showMonsterLog":false,"huntingBuffs2":"Deflect","showAmorTypeItems":true,"huntingBuffs":"Doubler,Librarian,Adept Learner,Merchant,Treasure Hunter,Animal Magnetism,Conserve","addAttackLinkToLog":true,"memberlist":"","useNewGuildLog":false,"highlightPlayersNearMyLvl":true,"itemRecipient":"","guildFrnd":"","bwNeedsRefresh":true,"guildEnmy":"","enableEnemyOnlineList":false,"buffLog":"","lastCompletedQuestPage":"","currentGoldSentTotal":0,"listOfEnemies":"","moveGuildList":false,"keepLogs":false,"guildSelf":"","enableFastWalk":false,"hideQuestNames":"","enableBioCompressor":true,"questBeingTracked":"","lastChatCheck":"0","hideGuildInfoMessage":false,"showAdmin":false,"showQuickDropLinks":false,"showCombatLog":false,"enableCreatureColoring":true,"enterForSendMessage":false,"showRelicMessages":true,"navigateToLogAfterMsg":true,"enableChatParsing":true,"lastPlayerLogCheck":"0","hideRecipeNames":"","guildOnlineRefreshTime":300,"disableComposingPrompts":false,"maxGroupSizeToJoin":11,"buyBuffsGreeting":"Hello {playername}, can I buy {buffs} for {cost} please?","wantedNames":"","showAmuletTypeItems":true,"hideQuests":false,"enhanceOnlineDots":true,"fsboxcontent":"","needToPray":false,"enableAttackHelper":false,"hideGuildInfoTrade":false,"showRingTypeItems":true,"hideKrulPortal":false,"showHuntingBuffs":true,"enableTempleAlert":false,"questsNotComplete":false,"checkForQuestsInWorld":false,"showFastWalkIconOnWorld":false,"alliestotal":0,"enableQuickDrink":false,"storeLastQuestPage":false,"disableItemColoring":false,"hideGuildInfoSecureTrade":true,"hideMatchesForCompletedMoves":false,"goldConfirm":"","contactList":"","showGvGMessages":true,"showRecallMessages":true,"ajaxifyRankControls":false,"gameHelpLink":true,"goldRecipient":"","showStatBonusTotal":false,"showPvPSummaryInLog":false,"hideRelicOffline":false,"huntingBuffs3Name":"Super Elite Slayer","sendClasses":"[\"Amber\", \"5611\"], [\"Amethyst Weed\", \"9145\"], [\"Blood Bloom\", \"5563\"], [\"Cerulean Rose\", \"9156\"], [\"Coleoptera Body\", \"9287\"], [\"Dark Shade\", \"5564\"], [\"Deathbloom\", \"9140\"], [\"Deathly Mold\", \"9153\"], [\"Greenskin Fungus\", \"9148\"], [\"Heffle\", \"5565\"], [\"Jademare\", \"5566\"], [\"Ruby Thistle\", \"9143\"], [\"Toad Corpse\",\"9288\"], [\"Trinettle\", \"5567\"], [\"Viridian Vine\", \"9151\"], [\"Mortar & Pestle\", \"9157\"], [\"Beetle Juice\", \"9158\"]","minGroupLevel":1,"enableGuildInfoWidgets":true,"huntingBuffs2Name":"PvP","lastWorld":"","guildPast":"","enableOnlineAlliesWidgets":true,"huntingBuffsName":"default","sendGoldonWorld":false,"bountyListRefreshTime":300,"maxCompressedLines":10,"lastNotStartedQuestPage":"","enhanceChatTextEntry":true,"doNotKillList":"","enableWantedList":false,"currentTile":"","showSpeakerOnWorld":false,"keepHelperMenuOnScreen":true,"goldAmount":"","trackKillStreak":true,"defaultMessageSound":"http://dl.getdropbox.com/u/2144065/chimes.wav","maxCompressedCharacters":250,"showQuickSendLinks":false,"lastActiveQuestPage":"","moveFSBox":false,"lastGuildLogCheck":"0","huntingMode":false,"fsboxlog":false}
I had done the clear everything already.

Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
on the settings page do a force refresh by pressing Ctrl-F5

**Comment by atompkins** [comment]
go to firefox menu - developer - Storage Inspector (Shift+F9)
Open Local Storage - http://www.fallensword.com
Are there any values in there that don't start with GM_ or hcs. ?
Can you see any big values in there?

**Comment by icd55mph** [comment]
nothing happened. I am on a mac, does that change things?
Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
Maybe, let me fire up a mac and see...

**Comment by icd55mph** [comment]
I find inspector but no storage
Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
in inspector there is a little cog in the upper right hand corner. click on
that.
left hand side under Default Firefox Developer Tools - click on storage
after that a storage tab will pop up which is the same thing

**Comment by icd55mph** [comment]
In local storage, fallen sword, everything starts with GM
Martin Hannu
icd55mph@centurylink.net

**Comment by atompkins** [comment]
I had a look at Martin's machine and for some reason clearing history wasn't clearing local storage properly. In storage inspector it all looked fine but when you JSON.stringify(localStorage) it was massive.
I had to do localStorage.clear() to fix it. I don't know if this is specific to MacOS Firefox or if it was just a result of overflowing the storage. It is conceivable that the overflow caused the storage to become corrupt.
I am going to change the title of this issue to create a new button in settings to clear local storage.

**Comment by atompkins** [comment]
Just had this problem on a windows machine
