### ISSUE TITLE
Quick buff GB/BM/Ext/Ri defective?

### ISSUE THREAD

**Issue by Rover2** [fallenswordhelper/fallenswordhelper#60]
After the latest update to 1507, the newly added line above the FS quick buff window still shows the correct buffs running but clicking on "Activate" just turn "On" without the buff being cast on myself.

**Comment by atompkins** [comment]
Hi, please tell us your operating system, browser and version, if you are using tampermonkey or greasemonkey and which version. Thanks.

**Comment by atompkins** [comment]
Confirmed. Looks like I changed the way we acquire current player name.

**Comment by Rover2** [comment]
Great, missed your first eMail yesterday.
BTW, the "move selected items to" on manage backpack ("b") ceased to 
work ages ago. Should I create a new issue for that?
Thanks & Greetings from Germany!

Am 17.09.2015 um 08:50 schrieb atompkins:

**Comment by atompkins** [comment]
yes please. who are you in-game?

**Comment by Rover2** [comment]
Will do.
Greetings,
Ghafla ;)

Am 17.09.2015 um 09:30 schrieb atompkins:

**Comment by atompkins** [comment]
3708d1a342d5694acef2a9c5af7ad4d36b9f2871
