### ISSUE TITLE
wazzimoto

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#647]
FS Helper has crashed for me on both Chrome and Mozilla since yesterday! have reinstalled both Chrome and Mozilla as well as Tampermonkey and FsHelper......

still nothing!

_Originally posted by @wazzimoto in https://github.com/fallenswordhelper/fallenswordhelper/issues/645#issuecomment-2016575484_

**Comment by atompkins** [comment]
cool. tell us which version of Chrome and Mozilla that you are trying to use.

**Comment by wazzimoto** [comment]
Mozzilla is version 115.9.1 and Chrome is 109.0.5414.168

Thanks for repy
Sent from my iPhone

On Mar 23, 2024, at 3:00 PM, Adrian Tompkins ***@***.***> wrote:

﻿

cool. tell us which version of Chrome and Mozilla that you are trying to use.

**Comment by atompkins** [comment]
we don't support Firefox ESR.
that chrome version is too old, you need to update it.

**Comment by wazzimoto** [comment]
Ahhh ok! Going to have to upgrade to windows 10 believe!!
Unless there is different ones to use!
Thanks!
Sent from my iPhone

On Mar 23, 2024, at 3:40 PM, Adrian Tompkins ***@***.***> wrote:

﻿

we don't support Firefox ESR.
that chrome version is too old, you need to update it.

**Comment by atompkins** [comment]
windows 7?

**Comment by wazzimoto** [comment]
Windows 8
Sent from my iPhone

On Mar 23, 2024, at 4:09 PM, Adrian Tompkins ***@***.***> wrote:

﻿

windows 7?

**Comment by atompkins** [comment]
what about supermium?

**Comment by wazzimoto** [comment]
Will check it out thanks!!
Sent from my iPhone

On Mar 23, 2024, at 4:42 PM, Adrian Tompkins ***@***.***> wrote:

﻿

what about supermium?

**Comment by wazzimoto** [comment]
Worked great!! Back up and running! Thanks a ton!!
Sent from my iPhone

On Mar 23, 2024, at 5:11 PM, Adrian Tompkins ***@***.***> wrote:

﻿

Closed #647<https://github.com/fallenswordhelper/fallenswordhelper/issues/647> as completed.
