### ISSUE TITLE
Expand HCS accordion menu on keypress

### ISSUE THREAD

**Issue by atompkins** [fallenswordhelper/fallenswordhelper#78]
09:25 10/Nov/2015
[ Report ]  Chironex says: hey man, just wanted to say great job on the FS helper. I had a suggestion for you. It used to be that when you hit the G it took you to the guild page AND it opened the guild menu on the left. Now it only takes you to the guild page but does not open the menu. Do you have any time to code that back in. I sort of miss it. Same if you hit P to go to player, open the character menu as well. Thanks. Great job.

**Comment by atompkins** [comment]
I dunno how old this functionality is but it pre-dates the current menu system.
Should be able to do a localStorage call to set the appropriate menu in the new page location.
hcs.nav.openIndex

**Comment by barnie995** [comment]
Ill tackle this one.  :)     Seems to me that all I have to do is change a class atribute in the relevant li tag to "nav-level-0 nav-heading nav-open"    instead of    "nav-level-0 nav-heading nav-closed"

**Comment by atompkins** [comment]
@barnie995 any progress?

**Comment by atompkins** [comment]
I'm taking this one because it's easy ;)
I'm adding `localStorage.setItem('hcs.nav.openIndex', '4');` to the key handlers for various keys
4 is the Guild section, 2 is the Character section

**Comment by barnie995** [comment]
xD. Yea, Ive been hella busy lately

**Comment by atompkins** [comment]
I want a preference for this, I don't like it
